### ISSUE TITLE
Prevent DirectVmConsumerNotAvailableException failure after flow start

### ISSUE THREAD

**Issue by Hooghof** [assimbly/runtime#198]
Sometimes, after the start of a flow, a failure arrises. The error below can be find in the logs. Recently, in a previous Camel 2 version, a solution was created for flowlinks with a longer timeout, so that all routes of a flow have time to start. 

```Failed delivery for (MessageId: DA6A6924F82B105-0000000000011639 on ExchangeId: DA6A6924F82B105-0000000000011639). Exhausted after delivery attempt: 1 caught: org.apache.camel.component.directvm.DirectVmConsumerNotAvailableException: No consumers available on endpoint: direct-vm://ID_6601a936d078790012003575_production_6f8d0bb4-d405-47a0-b8d8-88b9f3d606b4. Exchange[DA6A6924F82B105-0000000000011639]. Processed by failure processor: FatalFallbackErrorHandler[Channel[setExchangePattern62]] Message History --------------------------------------------------------------------------------------------------------------------------------------- Source ID Processor Elapsed (ms) xml:2 ID_6601a936d078790012003575-6f from[timer://ID_6601a936d078790012003575_timer?fix 2239572225 xml:3 ID_6601a936d078790012003575-6f direct-vm:ID_6601a936d078790012003575_production_6 0 xml:5 onException328/setExchangePatt setExchangePattern[InOnly] 0 Exchange --------------------------------------------------------------------------------------------------------------------------------------- Exchange[ Id DA6A6924F82B105-0000000000011639 Headers {breadcrumbId=DA6A6924F82B105-0000000000011639, CamelMessageTimestamp=1713860964954, CamelRedelivered=false, CamelRedeliveryCounter=0, firedTime=Tue Apr 23 08:29:24 UTC 2024} BodyType null Body [Body is null] ] Stacktrace ---------------------------------------------------------------------------------------------------------------------------------------```

**Comment by skin27** [comment]
In Camel 4 the error is: org.apache.camel.component.directvm.DirectConsumerNotAvailableException

On research this only occured when for example stopping a flow with pending messages. Then this error is as expected. I will close this issue for now, if need to investigate this on reproducible use case. 

There are two ways to mitigate it:

Either:

Set failIfNoConsumers to false

Or

enlarge the timeout 30000 to a higher value
