### ISSUE TITLE
Reinstall (Stop) flow doesn't work when there are pending messages

### ISSUE THREAD

**Issue by skin27** [assimbly/runtime#201]
Insights get the stats from the health-service of IJssel. However when IJssel is not available then we are getting pending messages. After IJssel is coming backup, we try to restart the flow on insights, but that doesn't work (because of a lock up).

Insights production issue: Can't reinstall flows after a while

**Comment by Hooghof** [comment]
If possible, it should be combined with these 2 user stories:
https://github.com/dovetailworld/front-end/issues/3905
https://github.com/dovetailworld/front-end/issues/3905

**Comment by skin27** [comment]
Nope, that's another type of issue.
