### ISSUE TITLE
Call on production endpoint gives Error 502 bad gateway

### ISSUE THREAD

**Issue by Hooghof** [assimbly/runtime#203]
A call on a production endpoint gives an Error 502 bad gateway. A call on the (same) test endpoint works as expected.

**Example flow**
Instance: insights
Tenant: Dovetail
Flow: MC_queue_test_out - https://insights.dovetail.world/flowdesigner/6638e50f1f83920012000307/3/route
Endpoint test: https://insights.dovetail.world/test/inbound_http/1/MC_queue_test_out
Endpoint production:  https://insights.dovetail.world/production/inbound_http/1/MC_queue_test_out

**Comment by brunovg** [comment]
After some investigations:
- calling each assimbly environment container directly from nginx container, works properly ✅ 
- calling from the main host of insights, we got a 502 on the production endpoint ❌ 
- checked nginx config file, and everything seems to be OK ✅ 

After a restart of nginx container, the production endpoint started to work properly ✅ 
At the end, we also did a redeploy on Insights, and everything was fine.

Let's see on the next following days if this happens again.
