### ISSUE TITLE
Unable to load exchanges

### ISSUE THREAD

**Issue by Hooghof** [assimbly/runtime#204]
The display of transaction exchanges is not possible sometimes, it shows anable to load exchanges.

![image (1)](https://github.com/assimbly/runtime/assets/23356235/fbe2ff23-68d5-4811-854f-d7e348f417ea)

Bruno says: on the old backend it’s filtering that case, and it doesn’t send to elasticsearch

**Comment by brunovg** [comment]
On the old backend (Karaf), some routes where filtered (when routeId contains `http_retry` or `_throttling`), before sent to ElasticSearch.
We need to add both cases on the new backend (Assimbly).

**Comment by Hooghof** [comment]
It is still not possible to see the exchanges

![Image](https://github.com/assimbly/runtime/assets/23356235/5e925117-92f7-4604-aa4e-1f18e1fb7e61)
