### ISSUE TITLE
Tracing is not displayed or stored well

### ISSUE THREAD

**Issue by Hooghof** [assimbly/runtime#213]
There are 3 variants:
1. The order of the exchanges is wrong
2. The only displayed component is the Inbound HTTP component (Instance: next, Tenant: Regression Tests, Flow: Velocity, Postman Test: Velocity headers)
3. There is no tracing at all (for example in case of the Base64 component option unmarshall), no distinction in transport type

**Comment by Hooghof** [comment]
Test findings:
- Most of the times, but not always, the individual exchanges are visible in the transactions now, except base64 marshall for example. Looks like it happens in case of transport type queues
- The order of exchanges is not always chronological
- The list of exchanges is getting longer after some tests

![Image](https://github.com/assimbly/runtime/assets/23356235/04ac084d-679a-468a-aafd-860be3316abf)

![Image](https://github.com/assimbly/runtime/assets/23356235/e2a71310-7dbc-4210-a403-e94b9c5c7d18)

![Image](https://github.com/assimbly/runtime/assets/23356235/7d36b8db-be0a-4e85-a879-019afde3d987)

**Comment by skin27** [comment]
Sometimes the tracing is not always in the right order. Norman didn't find a pattern yet, but will look into to get a reproducible thing.

**Comment by Hooghof** [comment]
It's not exactly reproducible how this hapens, but the order of exchanges differs per call. You can test in the flow Tracing01 on next (tenant Microscope), by sending a message body to this url: `https://next.dovetail.world/test/inbound_http/533057/Tracing01`

**Comment by Hooghof** [comment]
The order of the transactions' exchanges looks fine now.
What misses is the message body in every individual exchange. Only the last message body is shown.

![Image](https://github.com/assimbly/runtime/assets/23356235/f947f567-bd4f-41af-8824-c1fb841e872e)

![Image](https://github.com/assimbly/runtime/assets/23356235/91f0f524-d115-49d1-81a9-480a12da0440)
