### ISSUE TITLE
[Multipart]Doesn't generate output

### ISSUE THREAD

**Issue by Hooghof** [assimbly/runtime#215]
The multipart component gives no output in this case:

Instance: next
Tenant: Regression Tests
Flow: Multipart
Postman test: Multipart

**Comment by skin27** [comment]
This also works local. Need to check it with Bruno.

**Comment by brunovg** [comment]
Also works on my local machine.
I'm getting the following output:
````
----------------------------Assimbly
Content-Disposition: form-data; name="dovetail_multipart"; filename="UndefinedFileName"
Content-Type: application/json
Content-Transfer-Encoding: binary

body test
----------------------------Assimbly--

````

**Comment by skin27** [comment]
Yeah, that seems to be correct. Let's check it after the deployment.

**Comment by Hooghof** [comment]
After the deployment, the test gives the expected result.

**Comment by Hooghof** [comment]
Yesterday it worked, but not anymore today.
