### ISSUE TITLE
[Velocity]Use of ${headers} fails

### ISSUE THREAD

**Issue by Hooghof** [assimbly/runtime#216]
The use of ${headers} leads to http 500 error or empty response. The 500 error exists if the flow transport type is synchronous. The empty response if the transport type is queues. In both case the tracing is not right. If synchronous, there is no tracing at all. If queues, the first and last steps are missing.  

It is reproduced in this flow:
Instance: next
Tenant: Microscope:
Flow: HeadersInVelocity

In Dovetail 4.14.8/Camel 2and 4.16.0/Camel 3, ${headers} put all headers in the velocity component.

**Comment by skin27** [comment]
Seems a bug created a ticket on Camel jira:

https://issues.apache.org/jira/browse/CAMEL-20802

**Comment by skin27** [comment]
Set the CamelVelocityTemplate header as constant, instead of simple. For this this to test, the frontend needs to be rebuild/redeployed
