### ISSUE TITLE
[Oauth]Retrieve Google drive authorisation returns error

### ISSUE THREAD

**Issue by Hooghof** [assimbly/runtime#219]
Instance: next
Tenant: Regression Tests
Flow: OauthGoogleDrive

Error: Invalid OAuth2 token

https://github.com/assimbly/runtime/assets/23356235/d5161af9-80db-4607-8334-4c7a87696e07

**Comment by brunovg** [comment]
The endpoint `/api/oauth2token/info` was not present on the headless build.
