### ISSUE TITLE
[Split]XML aggregation transforms some characters

### ISSUE THREAD

**Issue by Hooghof** [assimbly/runtime#222]
Instance: next
Tenant: Regression Tests
Flow: SplitJson
Postman test: Comp-Routing / Split Json XmlAggregateRequestReply

For example a single quote is replaced by an elipsis.

**Expected**

`Als NYPD rechercheur Simpson (Chadwick Boseman) een operatie verknalt, krijgt hij nog één laatste kans om zijn baan te redden. Samen met zijn collega&#x92;s moet hij op Manhattan een voortvluchtige &#x91;cop killer&#x92; zien in te rekenen. Naarmate de nacht vordert, moeten er steeds extremere maatregelen worden genomen. Voor het eerst in de geschiedenis van New York worden alle 21 bruggen gesloten, zodat de moordenaar geen kant meer op kan. Zo wordt Manhattan voor één nacht een afgesloten eiland en is de jacht op de moordenaar geopend&#x85;`

**Result**
`
Als NYPD rechercheur Simpson (Chadwick Boseman) een operatie verknalt, krijgt hij nog één laatste kans om zijn baan te redden. Samen met zijn collega&#146;s moet hij op Manhattan een voortvluchtige &#145;cop killer&#146; zien in te rekenen. Naarmate de nacht vordert, moeten er steeds extremere maatregelen worden genomen. Voor het eerst in de geschiedenis van New York worden alle 21 bruggen gesloten, zodat de moordenaar geen kant meer op kan. Zo wordt Manhattan voor één nacht een afgesloten eiland en is de jacht op de moordenaar geopend&#133;
`

**Comment by brunovg** [comment]
I think the main problem is on the text itself

![Image](https://github.com/assimbly/runtime/assets/5382313/f5d0bde0-5fc0-4847-ab33-f5f195e8b70e)

**Comment by Hooghof** [comment]
I replaced the pinpointed characters in the input body and the result of the tests on development and next are equal now.
