### ISSUE TITLE
[SQL]Double insert of backslash if option Escape characters is enabled

### ISSUE THREAD

**Issue by Hooghof** [assimbly/runtime#229]
If the option `Escape characters?` in the SQL component is enabled, a backslash is inserted twice.
In case this value is inserted: {"body":"abc\ndef"}
Acceptance stores: {\"body\":\"abc\ndef\"}
Development stores: {\"body\":\"abc\ndef\"}
Next stores: {\"body\":\"abc\\\ndef\"}

Between `abc` and `ndef` there is an extra backslash

**Reproduction**
Instance: next
Tenant: Regression Tests
Flow: SQL (choices: insert_postgresql, insert_postgresql_escaped and insert_mysql8_escaped)
Postman tests: (SQL insert_postgresql, SQL insert_postgresql_escape and SQL insert_mysql8_escaped)

**Comment by brunovg** [comment]
Created the following simple flow test:
Development (Test BVG1) - https://development.dovetail.world/flowdesigner/666971249a8bd8000e00000e/1/route
Next (Bruno) - https://next.dovetail.world/flowdesigner/66696ae076f90a000a00000e/0/route
Acceptance (Test BVG) - https://acceptance.dovetail.world/flowdesign/666972fda2f8f60030000012

And I got the same results, with (second result) and without (first result) using escape chars:

![Image](https://github.com/assimbly/runtime/assets/5382313/650c176b-033a-463c-b95a-4b0d02c569dc)

**Comment by Hooghof** [comment]
I tested the same flow on acceptance, development and next. Next gives a different view. The insert queries are equal:

`INSERT into transaction (timestamp,breadcrumbId,server,tenant,environment,flow_id,flow_name,name,value) VALUES ('2024-06-14T16:47:21','6EB60CCC00333B5-0000000000080CCD_insert_mysql8_escaped','https://next.dovetail.world','Regression Tests','test','659bd6d5d377b7000b000002','SQL','body','{"body":"abc\ndef"}')`

The stored data in the column 'value' differs:

![Image](https://github.com/assimbly/runtime/assets/23356235/be8cec6c-43b5-437f-9e2f-908f1001e51c)
