### ISSUE TITLE
Groovy script error No such property: headerName for class

### ISSUE THREAD

**Issue by Hooghof** [assimbly/runtime#231]
If testing a groovy script with headers and body, this is the result: `Invalid groovy script: 'No such property: headerName for class: Script_28c5845e7c807fb5869cec43d20fc414'`

See test set attached.
[test set.zip](https://github.com/user-attachments/files/15606560/test.set.zip)

**Comment by skin27** [comment]
Het is best wel een uitgebreid script. Als het script niet werkt is het best het script in stukken te knippen en de afzonderlijke delen te testen.

Het meest verdacht zijn dan de import statement. In dit geval de import van Saxon ten behoeve van xpath. We gaan van Groovy 2.5 naar Groovy 4. In als de achterliggende Java libraries zoals Saxon gebruikt van Java 8 naar Java 21.

De Saxon library is best wel wat gewijzigd. Het volgende zou moeten werken:

```
import net.sf.saxon.s9api.*
import javax.xml.transform.stream.StreamSource;

// Create a Processor instance
Processor processor = new Processor(false)

// Create a DocumentBuilder and build the XML source
DocumentBuilder builder = processor.newDocumentBuilder()
XdmNode xmlDoc = builder.build(new StreamSource(new StringReader(body)))

// Create an XPathCompiler and compile an XPath expression
XPathCompiler xpathCompiler = processor.newXPathCompiler()
XPathSelector selector = xpathCompiler.compile("/root/element").load()

// Set the context item for the XPath expression
selector.contextItem = xmlDoc

// Evaluate the XPath expression and iterate over the results
XdmValue evaluated= selector.evaluate()

 result = evaluated[0].getStringValue()

return result;
```

Waarbij de input xml:

```xml
<root>
    <element>value2</element>
</root>
```

Getest op Next.

**Comment by skin27** [comment]
Action points:

1. How much is used
2. Alternative use xpath in headers

**Comment by Hooghof** [comment]
We discussed the use of Java libraries in groovy with WCG. Testing and changing scripts is part of their plan. If necessary we will be consulted by WCG.
