### ISSUE TITLE
[Base64]Cannot reset stream from file

### ISSUE THREAD

**Issue by Hooghof** [assimbly/runtime#233]
After the latest deployment, the processing of a file through base64 component results in a failure, this is the error message:

{
  "code": 500,
  "error": "org.apache.camel.RuntimeCamelException: Cannot reset stream from file /data/.assimbly/streamcache/cos8536356355650125853.tmp",
  "info": "Something went wrong calling the HTTP service. Please refer to the logs for more information."
}

**Test flow**
Instance: next
Tenant: Regression tests
Flow: Base64Marshall
Postman test: Base64Marshall

**Comment by skin27** [comment]
I looked at base64 further, and this goes wrong when the transport is set to Asynchronous. I have now set it to Synchronous for a while and the test should work again.

I do not know why exactly it goes wrong with Asynchronous. It seems to have lost contact with the previous step (even though the exchangepattern is set to InOut. I asked this queston on the Camel forum and put it on hold for now.

**Comment by skin27** [comment]
After investigating I turned of the caching to disk for now (This will (stream)cache in memory only.
