### ISSUE TITLE
Migration ComponentResponseTime

### ISSUE THREAD

**Issue by Hooghof** [assimbly/runtime#239]
In Camel 2 and 3 we had the ComponentResponseTime header or property. In Camel 4 it is called ResponseTime. This header/property is used in 291 production flows. I propose to write a migration for this, so that users don't have to change this name change manually.

**Comment by skin27** [comment]
This is the old way:

${header.componentResponseTime}

And this is the new way:

${property.ResponseTime}

**Comment by Hooghof** [comment]
Migration in components settings: ${header.ComponentResponseTime} into ${property.ResponseTime}
