### ISSUE TITLE
[FTP]install error on combination scheduler and FTP

### ISSUE THREAD

**Issue by Hooghof** [assimbly/runtime#252]
it is not possible to install a flow that starts with a schedule component which is followed by an FTP component (doesn't matter if the option force inbound is whether or not used).

**Test case**
Instance: next
Tenant: Regression tests
Flow: FtpMultipleFiles
Version: 5

Version 3, which starts with an inbound flowlink works fine.

**Error**

Name | FtpComponent
-- | --
Flow type | Default flow
Message | Only one input is allowed per route. Cannot accept input: From[ftp:dovetail@52.215.104.62/next/Regression Tests/test/in/?autoCreate=true&charset=utf-8&delete=false&recursive=false&delay=10000&initialDelay=1000&passiveMode=true&disconnect=true&throwExceptionOnConnectFailed=true&bridgeErrorHandler=true&password=RAW(Unmwrnf4bM3RUwoG)&include=RAW(.*.multi)&move=RAW(processed)&moveFailed=RAW(.error)&scheduler=quartz2&scheduler.cron=0+12+*+*+*+?&scheduler.timeZone=Europe/Amsterdam] in route_03b98cb0-b97e-4604-9226-e3070901a638.xml, line 3, column 507: <from uri="ftp:dovetail@52.215.104.62/next/Regression Tests/test/in/?autoCreate=true&amp;charset=utf-8&amp;delete=false&amp;recursive=false&amp;delay=10000&amp;initialDelay=1000&amp;passiveMode=true&amp;disconnect=true&amp;throwExceptionOnConnectFailed=true&amp;bridgeErrorHandler=true&amp;password=RAW(Unmwrnf4bM3RUwoG)&amp;include=RAW(.*.multi)&amp;move=RAW(processed)&amp;moveFailed=RAW(.error)&amp;scheduler=quartz2&amp;scheduler.cron=0+12+*+*+*+?&amp;scheduler.timeZone=Europe/Amsterdam"/> ^

**Comment by skin27** [comment]
The FTP is as follows:

```xml
	<route id="038f756f-a18c-4703-959e-f907476b4d01">
		<from uri="direct:ID_6685054bc44fd0000b00018b_test_52f61a53-ba5c-4d3a-aa15-fba9878af5b2"/>
		<from uri="ftp:dovetail@52.215.104.62/next/Regression Tests/test/in/?autoCreate=true&amp;charset=utf-8&amp;delete=false&amp;recursive=false&amp;delay=10000&amp;initialDelay=1000&amp;passiveMode=true&amp;disconnect=true&amp;throwExceptionOnConnectFailed=true&amp;consumer.bridgeErrorHandler=true&amp;password=RAW(Unmwrnf4bM3RUwoG)&amp;include=RAW(.*.multi)&amp;move=RAW(processed)&amp;moveFailed=RAW(.error)&amp;scheduler=quartz2&amp;scheduler.cron=0+12+*+*+*+?&amp;scheduler.timeZone=Europe/Amsterdam"/>
		<to uri="direct:ID_6685054bc44fd0000b00018b_test_038f756f-a18c-4703-959e-f907476b4d01"/>
	</route>
```

This route contains two **from** statements. In Camel 2 this wasn't recommended, but still possible. Since Camel 3 only one **from** statement is allowed.

I don't know exactly what this double statement do functionally. We can either made it:

1. Two routes
2. Pollenrich
3. To the second from into a two
4. Use scheduled into one route

Preferable the last one. Seems to be a combination of scheduler + ftp

**Comment by skin27** [comment]
Another option is to set the scheduler (cron) directly into the FTP component (a separate tab)?
