### ISSUE TITLE
[HTTP]Notification of 500 error after flow install (NTLM)

### ISSUE THREAD

**Issue by Hooghof** [assimbly/runtime#258]
**Test case**
Instance: next
Tenant: Regression tests
Flow: HttpNTLM

After a flow install this notification is displayed: Failed to install flow, for more detail please see the [Install logs page]

Install Log:

Name | HttpComponent
-- | --
Flow type | Default flow
Message | Failed to create route ID_669e484abaaec900140000c9-439b4434-6ea3-4c1b-9872-8e043eeb66d5 at: >>> step -> [[SetHeader[CamelHttpMethod, constant{GET}], SetHeader[user-agent, constant{Dovetail/4.17.0-SNAPSHOT}], SetProperty[useCustomDateHeader, constant{false}], To[bean:ntlmProcessor], To[https://next.dovetail.world/test/inbound_http/regressiontests/HttpCatchCalls?transferException=true&cookieStore=#flowCookieStore&headerFilterStrategy=#CustomHttpHeaderFilterStrategy&authMethod=NTLM&authUsername=xxxxxx&authPassword=xxxxxx&authDomain=RAW(domainBordeaux)&authHost=RAW()&throwExceptionOnFailure=false&sslContextParameters=#sslContext&maxTotalConnections=20&connectionsPerRoute=2&connectTimeout=180000&soTimeout=180000&lazyStartProducer=true], RemoveHeaders[CamelHttpMethod], RemoveHeaders[user-agent], To[direct:ID_669e484abaaec900140000c9_test_439b4434-6ea3-4c1b-9872-8e043eeb66d5]]] <<< in route: Route(ID_669e484abaaec900140000c9-439b4434-6ea3-4c1b-9872-8e... because of Failed to resolve endpoint: bean://ntlmProcessor due to: No bean could be found in the registry for: ntlmProcessor

**Comment by brunovg** [comment]
Basically it cannot find the NTLMProcessor that was added on Karaf (Camel2), to correct the following issue:
https://dovetailworld.atlassian.net/jira/servicedesk/projects/DOV/queues/custom/20/DOV-1510

For now, this will be also removed from the frontend.
In the feature, we need to test this with the customer.
