### ISSUE TITLE
[Http Retry] Impossible to see response body from 5xx responses

### ISSUE THREAD

**Issue by joepkalthoff** [assimbly/runtime#268]
### Summary
You can't find the response body from 5xx responses in the Flow Manager Logs or Transactions of a flow .
 
### Testcase
Dovetail version: 4.17.0-SNAPSHOT-dcb7cc8
Instance: next
Tenant: Regression Tests

Sending Flow: HttpRetrySocketAsynchronous
Flow version: 7
url: https://next.dovetail.world/flowdesigner/66b1efbde56ba4001000012e/7/route

Receiving Flow: HttpRetry500
Flow version: 1
url: https://next.dovetail.world/flowdesigner/66b31c0ee56ba4000e00002f/1/route

Input:
- Make sure the flow is installed in test and kick off the flow: https://next.dovetail.world/test/inbound_http/regressiontests/HttpRetrySocketAsynchronous

Output:
Check the Logs and Transactions of the Receiving flow. Try to find the response body of the 5xx statuscode responses that trigger the retry.

### Result
Below you see the last response from the Receiving flow in the transactions of the Sending flow. Notice the response body. After the second retry the Receiving flow responds with a 200 statuscode and a response body.
![Image](https://github.com/user-attachments/assets/979c789a-f2de-4a73-9328-e7e00a8446ff)

But the 5xx responses also had a body defined that you can't see / evaluate anywhere in the Flow Manager details:
![Image](https://github.com/user-attachments/assets/bbecf08d-7351-4e4a-8ef2-48a1d26095b0)

### Conclusion
There should be a way to see the response body of 5xx responses. The response body can contain valuable information about why the server responded with a 5xx statuscode. This gives the user a chance to fix underlying issues that cause the 5xx response in the first place.

Maybe we should create an entry in the Logs of the flow for showing the headers and body for each 5xx response?

This issue is related to the response headers that interfere with the retry messages, that is documented in a seperate issue: https://github.com/assimbly/runtime/issues/269.

Original issue on Dovetail Application board: https://github.com/dovetailworld/front-end/issues/4636.

**Comment by skin27** [comment]
There is already a mechanism that logs all relevant information. I assume this isn't probably referenced to the correct flow, so that it's not in log of the flow (only in the general log on the server). We will investigate this.

**Comment by joepkalthoff** [comment]
Where am I supposed to see the response body?

**Comment by joepkalthoff** [comment]
There is one other oddity, the first time the flow in the testcase recieves a Content-Type header with value: `application/json; charset: utf-8`

Each retry the Content-Type header's value is: `application/json`

The initial header is set with value: `application/json`

**Comment by brunovg** [comment]
PR: https://github.com/dovetailworld/front-end/pull/4769

**Comment by joepkalthoff** [comment]
Tested and response in log WARN entry is complete now.
