### ISSUE TITLE
Rename Dovetail header names

### ISSUE THREAD

**Issue by Hooghof** [assimbly/runtime#289]
As a user I like to rename the following header names, so that it not interferes with previously used headers and it also is in line with other specific Dovetail headers for the retrying mechanism:
- flowId into DOVETAIL_FlowId
- flowVersion into DOVETAIL_FlowVersion

**Comment by skin27** [comment]
I changed the headers. 

@brunovg It needs to be checked if transactions with flowlinks still work, before deploying

**Comment by brunovg** [comment]
internally we use different property names to register on ElasticSearch, so it should not be necessary.

**Comment by skin27** [comment]
OK, let's deploy it then.
