### ISSUE TITLE
[Replace]Different behavior of Replace with

### ISSUE THREAD

**Issue by Hooghof** [assimbly/runtime#293]
The value added in the 'Replace with' field are different processed in Camel 4 as in Camel 2. It concerns the values: `\n`, `\r` and `\t`. The expectation is that the value in the 'Replace with' field will replace the value in the 'Regex' field litterally. Looks like the 'Replace with' is interpreted as regex as well.

**Test case**
Instance: acceptance and development
Tenant: regression Tests
Flow: ReplaceWith
Tests in Postman: ReplaceWith CR /linefeed / tab
or in cURL (use 'development' in stead of 'acceptance' for the development instance) 

curl --location 'https://acceptance.dovetail.world/test/inbound_http/regressiontests/ReplaceWith?config=cr' \
--header 'Content-Type: text/plain' \
--data 'a,bCRc,dCRe,fCR'

curl --location 'https://acceptance.dovetail.world/test/inbound_http/regressiontests/ReplaceWith?config=linefeed' \
--header 'Content-Type: text/plain' \
--data 'a,bLNc,dLNe,fLN'

curl --location 'https://acceptance.dovetail.world/test/inbound_http/regressiontests/ReplaceWith?config=tab' \
--header 'Content-Type: text/plain' \
--data 'aTABb
cTABd
eTABf'

**Comment by skin27** [comment]
If possible, could you provide text files with:

1. Input
2. Expected output
3. Actual output

**Comment by skin27** [comment]
[cr_replace_acc.txt](https://github.com/user-attachments/files/17552866/cr_replace_acc.txt)
[cr_replace_dev.txt](https://github.com/user-attachments/files/17552867/cr_replace_dev.txt)

**Comment by skin27** [comment]
Attached examples for cr

**Comment by skin27** [comment]
Seems like we need to unescape the exceptional characters. This is a function from Camel. I added this so that it behaves like old way, but maybe in the future we can use a different approach.
