### ISSUE TITLE
Migration groovy script for xml support

### ISSUE THREAD

**Issue by Hooghof** [assimbly/runtime#294]
As a user I like to have a migration script for specific groovy scripts which need XML support, like xmlslurper. It turns out that we need to start a groovy script with `import groovy.xml.*;` in that case. The migration script should check if the groovy script needs xml support, in that case the first line needs to be inserted with: `import groovy.xml.*;`.

**Comment by skin27** [comment]
On hold: Customer find this migration to risky to use.
