### ISSUE TITLE
Migration flow properties environment

### ISSUE THREAD

**Issue by skin27** [assimbly/runtime#299]
After some research it turn that when custom flow properties were created that the were uppercase. A change made them uppercase. However we need to run a script on:

- local
- development
- next
- insights
- demo

To make all properties lowercase. New custom properties are automatically lowercase, so this isn't need for other environments.

**Comment by brunovg** [comment]
Migration script was executed on Development, please take a look.

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
**Tenant: dovetail**
 > iterate over flows
 dovetail > flow_id: 6311e4bbb0f180000e000013 > 12 (Test -> test)
 dovetail > flow_id: 6311e4bbb0f180000e000013 > 12 (Production -> production)
 dovetail > flow_id: 66d9724c9a7326001700020c > multipart (Test -> test)
 dovetail > flow_id: 66d9724c9a7326001700020c > multipart (Production -> production)
 dovetail > flow_id: 66d9724c9a7326001700020c > mumtipart (Test -> test)
 dovetail > flow_id: 66d9724c9a7326001700020c > mumtipart (Production -> production)
 dovetail > flow_id: 66d9724c9a7326001700020c > Mumtipart (Test -> test)
 dovetail > flow_id: 66d9724c9a7326001700020c > Mumtipart (Production -> production)
 dovetail > flow_id: 66d9724c9a7326001700020c > self.server1 (Test -> test)
 dovetail > flow_id: 66d9724c9a7326001700020c > self.server1 (Production -> production)
 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
**Tenant: regressiontests**
 > iterate over flows
 regressiontests > flow_id: 6719ed897151ef001a000051 > FlowProp1 (Test -> test)
 regressiontests > flow_id: 6719ed897151ef001a000051 > FlowProp1 (Production -> production)
 regressiontests > flow_id: 6719ed897151ef001a000051 > FlowProp2 (Test -> test)
 regressiontests > flow_id: 6719ed897151ef001a000051 > FlowProp2 (Production -> production)
 regressiontests > flow_id: 6720ec30c65b18001a0000a6 > AmazonAWSAccessKeyID (Test -> test)
 regressiontests > flow_id: 6720ec30c65b18001a0000a6 > AmazonAWSAccessKeyID (Production -> production)
 regressiontests > flow_id: 6720ec30c65b18001a0000a6 > AmazonAWSRegion (Test -> test)
 regressiontests > flow_id: 6720ec30c65b18001a0000a6 > AmazonAWSRegion (Production -> production)
 regressiontests > flow_id: 6720ec30c65b18001a0000a6 > AmazonAWSSecretAccessKey (Test -> test)
 regressiontests > flow_id: 6720ec30c65b18001a0000a6 > AmazonAWSSecretAccessKey (Production -> production)
 regressiontests > flow_id: 6720ec30c65b18001a0000a6 > AmazonAWSTarget (Test -> test)
 regressiontests > flow_id: 6720ec30c65b18001a0000a6 > AmazonAWSTarget (Production -> production)
 
 > iterate over flow_versions
 regressiontests > version_id: 6719ef6c7151ef0017000072 > FlowProp1 (Test -> test)
 regressiontests > version_id: 6719ef6c7151ef0017000072 > FlowProp1 (Production -> production)
 regressiontests > version_id: 6719ef6c7151ef0017000072 > FlowProp2 (Test -> test)
 regressiontests > version_id: 6719ef6c7151ef0017000072 > FlowProp2 (Production -> production)
 regressiontests > version_id: 6719f0ab7151ef001a0000bc > FlowProp1 (Test -> test)
 regressiontests > version_id: 6719f0ab7151ef001a0000bc > FlowProp1 (Production -> production)
 regressiontests > version_id: 6719f0ab7151ef001a0000bc > FlowProp2 (Test -> test)
 regressiontests > version_id: 6719f0ab7151ef001a0000bc > FlowProp2 (Production -> production)
 regressiontests > version_id: 671f3ed8c5a42c0018000037 > FlowProp1 (Test -> test)
 regressiontests > version_id: 671f3ed8c5a42c0018000037 > FlowProp1 (Production -> production)
 regressiontests > version_id: 671f3ed8c5a42c0018000037 > FlowProp2 (Test -> test)
 regressiontests > version_id: 671f3ed8c5a42c0018000037 > FlowProp2 (Production -> production)
 regressiontests > version_id: 671f3f64c5a42c000f000039 > FlowProp1 (Test -> test)
 regressiontests > version_id: 671f3f64c5a42c000f000039 > FlowProp1 (Production -> production)
 regressiontests > version_id: 671f3f64c5a42c000f000039 > FlowProp2 (Test -> test)
 regressiontests > version_id: 671f3f64c5a42c000f000039 > FlowProp2 (Production -> production)
 regressiontests > version_id: 6720f737b6e4f707b8000007 > FlowProp1 (Test -> test)
 regressiontests > version_id: 6720f737b6e4f707b8000007 > FlowProp1 (Production -> production)
 regressiontests > version_id: 6720f737b6e4f707b8000007 > FlowProp2 (Test -> test)
 regressiontests > version_id: 6720f737b6e4f707b8000007 > FlowProp2 (Production -> production)
 regressiontests > version_id: 67210450b6e4f707b8000094 > AmazonAWSAccessKeyID (Test -> test)
 regressiontests > version_id: 67210450b6e4f707b8000094 > AmazonAWSAccessKeyID (Production -> production)
 regressiontests > version_id: 67210450b6e4f707b8000094 > AmazonAWSRegion (Test -> test)
 regressiontests > version_id: 67210450b6e4f707b8000094 > AmazonAWSRegion (Production -> production)
 regressiontests > version_id: 67210450b6e4f707b8000094 > AmazonAWSSecretAccessKey (Test -> test)
 regressiontests > version_id: 67210450b6e4f707b8000094 > AmazonAWSSecretAccessKey (Production -> production)
 regressiontests > version_id: 67210450b6e4f707b8000094 > AmazonAWSTarget (Test -> test)
 regressiontests > version_id: 67210450b6e4f707b8000094 > AmazonAWSTarget (Production -> production)
 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
**Tenant: testbvg1**
 > iterate over flows
 testbvg1 > flow_id: 65df5be23b3095000b00018c > NewProperty (Test -> test)
 testbvg1 > flow_id: 65df5be23b3095000b00018c > NewProperty (Production -> production)
