### ISSUE TITLE
[Aggregate] Add header or property CamelAggregatedSize

### ISSUE THREAD

**Issue by Hooghof** [assimbly/runtime#311]
As a user I like to know how many aggregations were done in the outgoing message, so that I can optimize the aggregation options in the component to make the full integration more efficient.

If it is possible I like to know as well how much time was necessary to complete the aggregation with the set parameters in a header or property.

**Comment by skin27** [comment]
These properties are available by Camel:

![Image](https://github.com/user-attachments/assets/8aa52956-d58c-4dcc-a34c-0942f9422d59)

**Comment by Hooghof** [comment]
Create a new example with the Completion count option as a message header, using the option completionSizeExpression.

**Comment by skin27** [comment]
To implement this request the following needs to be done:

1. Frontend (React)

On the aggregate component the field "Completion count" needs to be changed from:

          integer ---> string

The header option should be added (now only flow properties) to the label.          

2. Frontend (Ruby)

Currently, the following XML code is generated:

```xml
		<aggregate strategyRef="XmlAggregateStrategy" completionSize="3">
			<correlationExpression>
				<constant>true</constant>
			</correlationExpression>
			<to uri="activemq:66d8183cb739040a18001c57_test_d6f04322-88b0-475d-b53d-1a22b1680951_aggregator?timeToLive=86400000&amp;requestTimeout=20000"/>
		</aggregate>
```

This needs to be changed to:

```xml
		<aggregate strategyRef="XmlAggregateStrategy">
			<correlationExpression>
				<constant>true</constant>
			</correlationExpression>
                        <completionSizeExpression>
                            <simple>XXX</simple>
                        </completionSizeExpression>
			<to uri="activemq:66d8183cb739040a18001c57_test_d6f04322-88b0-475d-b53d-1a22b1680951_aggregator?timeToLive=86400000&amp;requestTimeout=20000"/>
		</aggregate>
```

This means:

1. The 'completionSize' attribute needs to be removed.
2. The completionSize element needs to be added:

                        <completionSizeExpression>
                            <simple>XXX</simple>
                        </completionSizeExpression>

3. XXX is the value entered by the user as Completion count

**Comment by Hooghof** [comment]
The header variable as Completion count option works as expected.
