### ISSUE TITLE
Investigate if connection errors can be shown to users or alerts

### ISSUE THREAD

**Issue by Hooghof** [assimbly/runtime#313]
As a user, I would like to see failed exchanges in FM when there are errors when not being able to retrieve files via the Inbound Google Drive component, so that I am aware that there are errors that need to be fixed.

![Image](https://github.com/user-attachments/assets/0ce249a4-1048-4abd-8f37-976d7fc169bd)

**Comment by skin27** [comment]
This counts for:

InboundGoogleDrive
FTP
InboundEmail
Samba
etc

Best to this based on the logging in Elastic.

**Comment by skin27** [comment]
Another is that most components have the option "bridgeErrorHandler". When implemented it can send error as message to the errorhandler/error route:

"Allows  for bridging the consumer to the Camel routing Error Handler, which  mean any exceptions (if possible) occurred while the Camel consumer is  trying to pickup incoming messages, or the likes, will now be processed  as a message and handled by the routing Error Handler. Important: This  is only possible if the 3rd party component allows Camel to be alerted  if an exception was thrown. Some components handle this internally only,  and therefore bridgeErrorHandler is not possible. In other situations  we may improve the Camel component to hook into the 3rd party component  and make this possible for future releases. By default the consumer will  use the org.apache.camel.spi.ExceptionHandler to deal with exceptions,  that will be logged at WARN or ERROR level and ignored.
"

A few components that support this are :

File
SFTP
Jetty
Email
Google Drive (Default)
SMB
RabbitMQ
SQL

For some we may already enable this, but I can try to investigate if we can enable this globally.

**Comment by skin27** [comment]
Investigated finished and discussed. I'll make two separate tickets:

1. Implement global bridgeErrorHandler
2. Implement healt check API.
